# Generated by Django 4.0.4 on 2022-05-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntryModels',
            new_name='Entry',
        ),
    ]
